---
#
# User configuration
#
user:
  name: brian
  full_name: "brian"
  primary_group: users
  additional_groups: wheel
  # /bin/bash or /bin/zsh
  shell: /bin/zsh
  # See country list by running `reflector --list-countries`
  country: "United States"

git:
  name: "{{ user['full_name'] }}"
  # obfuscated a little so bots won't find it
  email_b64: "YnJpYW5raW01M0BnbWFpbC5jb20="

#
# Miscellaneous
#

# desktop environment to install
# "kde" or "gnome"
desktop: sway

# only AMD or Intel CPUs are currently supported
# true or false
install_microcode: true

# whether to enable printing/scanning or not
# true or false
enable_printing: false

# whether to detect the scanner or not
# true or false
detect_scanner: false

# whether to enable bluetooth or not
# true or false
enable_bluetooth: false

# whether to install laptop tools
# true or false
laptop: false

# how many parallel downloads to run at once
pacman:
  parallel_downloads: 10

# set aur helper
# supported helpers are here https://github.com/kewlfft/ansible-aur#kewlfftauraur-module
aur_helper: yay

#
# Services
#

# if not using systemd homed, disable it
# true or false
disable_systemd_homed: true

#
# Packages
#
packages:
  # - chromium
  - curl
  - dunst
  - eza
  - firefox
  - flatpak
  - fzf
  - gsimplecal
  - git
  - gvfs
  - gvfs-smb
  - htop
  - imv
  - lazygit
  # - libreoffice-still
  - linux-firmware
  - lf
  - man-db
  - man-pages
  - mpv
  - mupdf
  - ncdu
  - neofetch
  - neovim
  - networkmanager
  - pipewire
  - pipewire-alsa
  - pkgstats
  - prettier
  - r
  - ripgrep
  - rsync
  - shfmt
  - stylua
  - sudo
  - tesseract
  # - texlive-binextra
  # - texlive-fontsextra
  # - texlive-fontsrecommended
  # - texlive-latex
  # - texlive-latexextra
  # - texlive-latexrecommended
  # - texlive-luatex
  - thunar
  - tree
  - usbutils
  - unzip
  - vim
  - wget
  - wireplumber
  - yt-dlp
  - zathura
  - zathura-pdf-mupdf
  - zellij
  - zstd
  - zsh
  # wayland
  - bemenu
  - foot
  - grim
  - slurp
  - waybar
  - wl-clipboard
  - wofi

aur_packages:
  - clipman
  - ueberzugpp
  - wl-gammarelay

flatpaks:
  - com.discordapp.Discord
  - org.gimp.GIMP
  # - org.libreoffice.LibreOffice
  # - org.mozilla.Thunderbird

base_fonts:
  - ttf-firacode-nerd
  - ttf-iosevka-nerd
  - ttf-nerd-fonts-symbols-mono
  - ttf-sourcecodepro-nerd
  - ttf-terminus-nerd
  - ttf-cascadia-code

# printing_scanning_packages:
#   - cups
#   - cups-pdf
#   - sane
#   - sane-airscan
#   - simple-scan

# printing_scanning_aur_packages:
#   - brlaser-git
#   - brscan4
