---
- name: Git config user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git.name }}"

- name: Git config user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git.email_b64 | b64decode }}"

# - name: Get dotfiles
#   ansible.builtin.get_url:
#     url: '{{ item.src }}'
#     dest: '{{ item.dest }}'
#     mode: 0644
#     owner: "{{ user.name }}"
#     group: "{{ user.primary_group }}"
#   with_items:
#     - { src: 'https://raw.githubusercontent.com/brianfabre/dotfiles/main/.aliases', dest: '/home/brian/.aliases' }
#     - { src: 'https://raw.githubusercontent.com/brianfabre/dotfiles/main/.vimrc', dest: '/home/brian/.vimrc' }
#     - { src: 'https://raw.githubusercontent.com/brianfabre/dotfiles/main/.bashrc', dest: '/home/brian/.bashrc' }
#     - { src: 'https://raw.githubusercontent.com/brianfabre/dotfiles/main/.zshrc', dest: '/home/brian/.zshrc' }
#     - { src: 'https://raw.githubusercontent.com/brianfabre/dotfiles/main/.p10k.zsh', dest: '/home/brian/.p10k.zsh' }

- name: Update makepkg configuration file
  ansible.builtin.template:
    src: makepkg.conf
    dest: "/home/{{ user.name }}/.makepkg.conf"
    backup: no
    owner: "{{ user.name }}"
    group: "{{ user.primary_group }}"
    mode: 0644

- name: Mask systemd services - systemd homed
  ansible.builtin.systemd:
    name: "{{ item }}"
    masked: yes
  become: true
  with_items:
    - systemd-homed.service
    - systemd-userdbd.service
    - systemd-userdbd.socket
  when: disable_systemd_homed
