---
- name: Install desktop environment
  when: desktop == "kde"
  block:
    - name: Install Plasma
      community.general.pacman:
        name:
          - plasma-meta
          - plasma-wayland-session
          - kde-graphics-meta
          - kde-multimedia-meta
          - kde-network-meta
          - kde-pim-meta
          - kde-sdk-meta
          - kde-system-meta
          - kde-utilities-meta
          - sddm
          - xdg-desktop-portal-kde
        state: present
      become: true

    - name: Start systemd service - sddm.service
      ansible.builtin.systemd:
        name: sddm.service
        enabled: yes
      become: true

- name: Install desktop environment
  when: desktop == "sway"
  block:
    - name: Install Sway
      community.general.pacman:
        name:
          - sway
          - sddm
        state: present
      become: true

    - name: Start systemd service - sddm.service
      ansible.builtin.systemd:
        name: sddm.service
        enabled: yes
      become: true
